### ISSUE TITLE
Update authentication mechanism

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-provbz-auth#5]
Auth has changed from shibboleth to something similar to a propritary API.

Link to docs: https://servicemanual.services.siag.it/#/nuts-and-bolts/user-authentication/?id=ssocivisbzit
Swagger: https://sso.civis.bz.it/swagger/index.html

 
##### Step1: call to `/api/Auth/Login `

Params:
- `targetUrl`: URL for wich the session token is needed
- `acceptedAuthTypes`: list of auth methods requested
- `serviceUID`: OPENDATA
- `authLevel`:  authentication level i.e. spid is 2. Default is 0
- `onlyauth`:  authentication only or also possibility to retrieve user profile data. Default false
- `lang`: it/de
- `forceLogin`: default false

 As a response to the step 1 we get the URL toward the mycivis portal

##### Step 2: authentication

![image](https://github.com/user-attachments/assets/e9b8ad4b-04be-4098-8fc3-0135e57e8adc)

After the login you'll get the auth token, e.g. `?token=iromuzdn28uudjozimc2olxhxdv5hnigzh34eju9vi3hiqgcod92fckjhu8sicbu`

Using the token you can 
- verify the session validation `/api/Auth/Validate/{token}`
- get the user profile `/api/Auth/Profile/{token}`  -- the `onlyAuth` param should be set as in the login call 

 ##### Step 3: logout
 
At the end of the session call `/api/Auth/Logout`

  
The auth server has a host whitelist for the hosts that needs to use the auth services.
localhost is always whitelisted, for all the other hosts we'll need to ask whitelisting for the domains calling sso.civis.bz.it

**Comment by etj** [comment]
Full login procedure for CKAN system:

- The user clicks in the "mycivis" button
  ![image](https://github.com/user-attachments/assets/d40f1fd0-ac29-4e8c-a47f-cb901525a2ba)
- The user will be redirected to https://sso.civis.bz.it/api/Auth/Login, where the `targetUrl` will point back to a CKAN URL that will take care to 
  - retrieve the token from the URL
  - validate the token via the SSO API 
  - retrieve the user info from the SSO system
  - create an internal CKAN user if it doesn't exist yet 
  - redirect the user to the main CKAN page

**Comment by Gpetrak** [comment]
Thank you @etj  for the detailed description of the issue. [Here](https://github.com/geosolutions-it/ckanext-provbz-auth/pull/6) you can find the PR.

**Comment by etj** [comment]
Closed in branch 2.10.x
